### ISSUE TITLE
smarty plugin html_date_select and time set to NULL behaviour

### ISSUE THREAD

**Issue by danielbush** [uqlibrary/fez#24]
Hi,
I want to use time=NULL for html_select_date smarty plugin (docs: http://www.smarty.net/docs/en/language.function.html.select.date.tpl ).
I think there's a change to this plugin in fez which is affecting the NULL behaviour - see https://github.com/uqlibrary/fez/commit/99bfc185ce1dfe50ed219b73643ec8927c5265bb#commitcomment-11169526

Something like

```php
    if ($time !== null) {
        $params['time'] = trim($params['time']);
    }
```

If you apply the above and then do ```{html_select_date time=NULL ... }``` in enter_metadata.tpl.html and then create a new record that uses a date field, you should get blank day / month drop downs.

**Comment by ZoomShiny** [comment]
That sounds good. I've committed it to main branch

https://github.com/uqlibrary/fez/commit/29f5189a8a1d73c34d69b55692eac26ad449d51a.
