### ISSUE TITLE
windows based - docker setup error

### ISSUE THREAD

**Issue by mahen3d** [uqlibrary/fez#27]
docker based on windows setup ends up with following error

mxxx@SCULLY MINGW64 ~/UQLib/fez/.docker/development (master)
$ docker-compose up -d
development_logs_1 is up-to-date
development_fezdbdata_1 is up-to-date
development_cache_1 is up-to-date
development_fezdb_1 is up-to-date
development_fedoradbdata_1 is up-to-date
development_fedoradb_1 is up-to-date
development_solrdata_1 is up-to-date
development_fedoradata_1 is up-to-date
development_fedora_1 is up-to-date
development_solr_1 is up-to-date
Starting development_fpmb_1
[31mERROR[0m: Container command not found or does not exist.

Something wrong in the "fpmb:" setup 
or 
the "ENTRYPOINT ["/opt/bootstrap.sh"]"

**Comment by ckortekaas** [comment]
This likely fixed by https://github.com/uqlibrary/fez/commit/0991a3aabc6b725e98164df302d78f3adf074baa

**Comment by ckortekaas** [comment]
Closing this issue. Others are using docker for windows (beta) without issues and the raised error was likely fixed by the commit mentioned in the previous message.
