### ISSUE TITLE
docker development setup

### ISSUE THREAD

**Issue by danielbush** [uqlibrary/fez#33]
Hi Guys,
Had a go with the docket development setup instructions.
A lot of good work here to automate setting up a dev!

I ran into an issue however.
So, firstly, I'm using docker 1.11.2 and docker-compose version 1.8.0.

I did

``` bash
cd .docker/development
docker-compose up -d
```

(actually I'm using sudo because my user isn't in docker group).

So, all the containers came up.
I set up a reverse proxy so that dev-fez.library.uq.edu.au is in my host webserver and proxies to the fez_development_1 container which exposes 8080.

It then sent me to `/setup`.
Had to do this:

``` bash
sudo docker exec -u 0 -it development_fez_1 bash -c "mkdir /var/app/current/public/templates_c && chown -R nobody:nobody /var/app/current/public/templates_c"
```

and then:

``` bash
sudo docker exec -u 0 -it development_fez_1 bash -c "touch /var/app/current/public/config.inc.php && chown nobody:nobody /var/app/current/public/config.inc.php"
```
- That made the installer happy, and it took me to database name and credentials screen.
- I changed the database password, clicked submit.
- Then I got a browser alert box warning me the next step would take several minutes.
- Clicked ok.
- Then got a 500.

The url is: http://dev-fez.library.uq.edu.au/setup/index.php?step=2 .

I tried looking in the fez_development and fpm containers to see if there is an application or error log but there doesn't appear to be much in /var/log (a lot of directories but not much by way of log files).

I'll try to have another poke around, but is there a log file somewhere I can look at that might give me some more details?

**Comment by danielbush** [comment]
Actually, I just went back and tried again but this time didn't set the database password.  This time the system didn't give a 500.  But a short while late I got a gateway timeout (504).

**Comment by ckortekaas** [comment]
@danielbush could you try running scripts/dev.sh instead of the manual docker-compose up -d / execs? It takes care of the problems you're having IIRC.

**Comment by ckortekaas** [comment]
@danielbush I'm not 100% sure about your networking setup, but we've had success just finding the IP of the docker-machine VM and editing your (OSX or windows) hosts file and adding the aliases. E.g. (your ip will be different - run docker-machine ip fez-vm): 172.16.16.128 dev-fez.library.uq.edu.au
